name: Release Subu5

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            livecd-rootfs \
            xorriso \
            squashfs-tools \
            grub-pc-bin \
            grub-efi-amd64-bin \
            grub-efi-amd64-signed \
            shim-signed \
            mtools \
            dosfstools \
            rsync \
            debootstrap

      - name: Build
        run: |
          chmod +x scripts/build.sh
          sudo ./scripts/build.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            output/*.iso
